[package]
name = "gelsemium"
version = "0.1.0"
edition = "2024"

[dependencies]
rodio = {version = "0.22.2", features = ["symphonia-all"]}
slint = "1.17.1"

[build-dependencies]
slint-build = "1.17.1"

[lints.clippy]
pedantic = "warn"
unwrap_used = "warn"
expect_used = "warn"
indexing_slicing = "warn"
string_slice = "warn"
panic = "warn"
panic_in_result_fn = "warn"
exit = "warn"
todo = "warn"
# IMO this lint often makes code *less* readable.
needless_return = {level = "allow", priority = 1}
