import { Button, VerticalBox, TextEdit, HorizontalBox } from "std-widgets.slint";
// import "./LeagueMono-VF.ttf";

struct SongOrFolder{
    name: string,
    nest_level: int,
}

// Display the songs in the library.
component SongLibrary inherits Rectangle{
    in property<[SongOrFolder]> song_names: [
        {name: "examplesong1", nest_level: 0}, 
        {name: "examplesong2", nest_level: 1}, 
        {name: "examplesong3", nest_level: 2}, 
        {name: "examplesong4", nest_level: 0}];
    background: #672b78;
    property<length> offset_per_nest: 10px;

    VerticalLayout{
        alignment: start;
        for song[i] in song_names: HorizontalBox{
            x: offset_per_nest*song.nest_level;
            alignment: start;
            Text{
                text: song.name;
                horizontal-alignment: start;
            }
        }
    }   
}

// Queue of currently-playing songs.
component SongQueue inherits Rectangle{
    in property<[string]> song_names: [
         "examplesong1", 
         "examplesong2", 
         "examplesong3",
         "examplesong4",
    ];
    background: #672b78;
    property<length> offset_per_nest: 10px;

    VerticalLayout{
        alignment: start;
        for song[i] in song_names: HorizontalBox{
            alignment: start;
            Text{
                text: song;
                horizontal-alignment: start;
            }
        }
    }
    
}

component PlayerControls inherits Rectangle{
    property<length> icon_size: 50px;
    min-height: icon_size;
    max-height: icon_size;
    min-width: 2*icon_size;
    max-width: 2*icon_size;
    // Control buttons.
    HorizontalBox {
        alignment: center;
        Image{
            source: @image-url("playbutton.svg");
            colorize: #fbb5fb;
        }
        Image{
            // source: @image-url("skipbutton.svg");
            colorize: #fbb5fb;
        }
    }
}

// Component that displays when a playlist is being played currently.
component PlayingMenu inherits Rectangle{
    in property<[string]> song_names: [
         "examplesong1", 
         "examplesong2", 
         "examplesong3",
         "examplesong4",
    ];
    callback skip();
    callback pause();

    HorizontalBox {
        alignment: stretch;

        VerticalBox {
            width: 50%;
            // Album cover.
            Image{
                height: 30%;
            }
            // Skip/play/etc.
            PlayerControls {

            }
            SongQueue{
                song_names: song_names;
            }
        }
        
        
        SongLibrary {
            width: 50%;

        }
    }
}

component PlaylistPlayable inherits Rectangle{
    width: 90%;
    background: #f74cf7;
    in property <string> playlist_name;
    callback clicked(string);
    
    HorizontalBox{
        // name
        Text{
            height: 70px;
            text: playlist_name;
            horizontal-alignment: left;
            font-size: 36pt;
        }
        // spacer
        Rectangle{}
        // play button
        Image{
            source: @image-url("playbutton.svg");
            colorize: #fbb5fb;
            TouchArea{
                clicked => { root.clicked(playlist_name); }
            }
        }
    }
}

component PlaylistSelect inherits Rectangle{
    background: #f675f6;
    callback play_clicked(string);
    in property<[string]> playlist_names: ["Example Playlist", "Example Playlist 2.0"];

    Rectangle {
        width: 50%;
        height: 80%;
        background: #672b78;
        VerticalBox{
            alignment: start;
            for playlist_name in playlist_names: 
                PlaylistPlayable{
                    playlist_name: playlist_name;
                    clicked(s) => play_clicked(s);
            }
        }
    }
}

enum ScreenState{ select, playing, editing}
export component AppWindow inherits Window {
    callback play_playlist(string);

    callback get_playlist_song_list(string) -> [SongOrFolder];

    in property <[string]> playlist_names: ["Example Playlist", "Example Playlist 2.0"];
    in property <[string]> songs_for_selected;
    title: "Gelsemium Music Player";
    // default-font-family: "League Mono";

    property <ScreenState> state: select;
    if state == ScreenState.select: PlaylistSelect{
        playlist_names: playlist_names;
        play_clicked(playlist_name) => {
            state = ScreenState.playing;
            play_playlist(playlist_name);
        };
    }
    if state == ScreenState.playing: PlayingMenu{
        song_names: songs_for_selected;
    }
    
}


