import { Button, VerticalBox, TextEdit, HorizontalBox, ScrollView, ListView } from "std-widgets.slint";
// import "./LeagueMono-VF.ttf";

struct LibraryElem{
    name: string,
    nest_level: int,
    is_folder: bool,
    is_hidden: bool,
}

// Display the songs in the library.
component SongLibrary inherits Rectangle{
    in property<[LibraryElem]> song_names: [
        {name: "folder1", nest_level: 0, is_folder: true}, 
        {name: "examplesong1", nest_level: 1, is_folder: false}, 
        {name: "folder2", nest_level: 1, is_folder: true, is_hidden: false}, 
        {name: "examplesong3", nest_level: 2, is_folder: false}, 
        {name: "examplesong4", nest_level: 0, is_folder: false}];
    background: #672b78;
    property<length> offset_per_nest: 20px;
    callback library_elem_clicked(int);
    property<length> lib_width: self.width;

    ListView{
        for song[i] in song_names: HorizontalLayout{
            padding: 2px;
            x: offset_per_nest*song.nest_level + 5px;
            alignment: start;
            preferred-height: !song.is_hidden ? 22px : 0px;

            if !song.is_hidden: Rectangle{
                preferred-width: lib_width - parent.x;
                TouchArea{
                    preferred-height: 100%;
                    preferred-width: 100%;
                    Text{
                        x: 0;
                        text: song.name;
                        horizontal-alignment: start;
                    }
                    clicked => library_elem_clicked(i);
                }
            }
                
            
        }
    }   
}

// Queue of currently-playing songs.
component SongQueue inherits Rectangle{
    in property<[string]> normal_song_queue: [
         "examplesong1", 
         "examplesong2", 
         "examplesong3",
         "examplesong4",
    ];
    in property<[string]> immediate_queue: [
        "examplesong_a",
        "examplesong_b",
    ];
    in-out property<string> currently_playing: "current_playing";

    in property<brush> queue_background: #672b78;

    callback song_finished() -> string;
    callback notify_song_finished();
    notify_song_finished => {
        currently_playing = song_finished();
    }

    background: #f675f6;
    property<length> offset_per_nest: 10px;

    VerticalBox{
        // Currently-playing song.
        Rectangle{
            background: queue_background;
            HorizontalBox{
                alignment: start;
                Text{
                    text: currently_playing;
                    horizontal-alignment: start;
                }
            }
        }

        // User-constructed queue.
        if immediate_queue.length > 0: Rectangle{
            background: queue_background;
            ListView {
                for song[i] in immediate_queue: HorizontalBox{
                    alignment: start;
                    Text{
                        text: song;
                        horizontal-alignment: start;
                    }
                }
            }   
        }

        // Playlist.
        Rectangle{
            background: queue_background;
            ListView {
                for song[i] in normal_song_queue: HorizontalBox{
                    alignment: start;
                    Text{
                        text: song;
                        horizontal-alignment: start;
                    }
                }
            }   
        }
    }
}

component PlayerControls inherits Rectangle{
    property<length> icon_size: 50px;
    min-height: icon_size;
    max-height: icon_size;
    min-width: 2*icon_size;
    max-width: 2*icon_size;
    width: 100%;

    callback pause();
    callback skip();

    property<bool> paused: false;

    // Control buttons.
    HorizontalBox {
        alignment: center;
        Image{
            source: paused ? @image-url("pausebutton.svg") 
                           : @image-url("playbutton.svg");
            colorize: #fbb5fb;
            TouchArea{
                clicked => {
                    paused = !paused;
                    pause()
                };
            }
        }
        Image{
            source: @image-url("skipbutton.svg");
            colorize: #fbb5fb;
            TouchArea{
                clicked => skip();
            }
        }
    }
}

// Component that displays when a playlist is being played currently.
component PlayingMenu inherits Rectangle{
    in property<[string]> playlist_queue: [
         "examplesong1", 
         "examplesong2", 
         "examplesong3",
         "examplesong4",
    ];
    in property<[string]> user_queue: [
        "examplesonga", 
        "examplesongb", 
        "examplesongc",
        "examplesongd",
    ];
    in property<string> currently_playing: "current_playing";
    
    callback skip();
    callback pause();
    callback back_to_menu();

    in property<[LibraryElem]> library;
    callback library_elem_clicked(int);

    background: #f675f6;

    Image{
        source: @image-url("backbutton.svg");
        colorize: #fbb5fb;
        height: 30px;
        x: 5px;
        y: 5px;
        TouchArea{
            clicked => back_to_menu();
        }
    }

    HorizontalBox {
        alignment: stretch;

        VerticalBox {
            width: 50%;
            // Album cover.
            Image{
                // source: @image-url("playbutton.svg");
                // image-fit: cover;
                height: 30%;
            }
            // Skip/play/etc.
            PlayerControls {
                skip => skip();
                pause => pause();
            }
            songqueue := SongQueue{
                normal_song_queue: playlist_queue;
                immediate_queue: user_queue;
                currently_playing: currently_playing;   
            }
        }
        
        
        SongLibrary {
            width: 50%;
            song_names: library;
            library_elem_clicked(index) => library_elem_clicked(index);
        }
    }
}

component PlaylistPlayable inherits Rectangle{
    // width: 90%;
    background: #f74cf7;
    in property <string> playlist_name;
    callback play_clicked(string);
    callback edit_clicked(string);

    HorizontalBox{
        // name
        Text{
            font-family: "League Mono";
            height: 70px;
            text: playlist_name;
            horizontal-alignment: left;
            font-size: 36pt;
        }
        // spacer
        Rectangle{}
        // edit button
        Image{
            source: @image-url("settings.svg");
            colorize: #fbb5fb;
            TouchArea{
                clicked => { root.edit_clicked(playlist_name); }
            }
        }
        // play button
        Image{
            source: @image-url("playbutton.svg");
            colorize: #fbb5fb;
            TouchArea{
                clicked => { root.play_clicked(playlist_name); }
            }
        }
    }
}

component PlaylistSelect inherits Rectangle{
    background: #f675f6;
    callback play_clicked(string);
    callback edit_clicked(string);
    in property<[string]> playlist_names: ["Example Playlist", "Example Playlist 2.0"];

    Rectangle {
        width: 50%;
        height: 80%;
        background: #672b78;
        VerticalBox{
            alignment: start;
            for playlist_name in playlist_names: 
                PlaylistPlayable{
                    playlist_name: playlist_name;
                    play_clicked(s) => play_clicked(s);
                    edit_clicked(s) => edit_clicked(s);
            }
        }
    }
}

enum ScreenState{ select, playing, editing}
export component AppWindow inherits Window {
    // For the PlayingMenu state.
    callback pause();
    callback volume_up();
    callback volume_down();
    callback skip();
    callback library_elem_clicked(int);
    callback back_to_menu();
    in property <[string]> playlist_queue;
    in property <[string]> user_queue;
    in property <string> currently_playing;
    in property <[LibraryElem]> library;

    // For the PlaylistSelect state.
    callback play_playlist(string);
    callback edit_playlist(string);
    in property <[string]> playlist_names: ["Example Playlist", "Example Playlist 2.0"];

    // For the PlaylistEdit state.

    // General properties.
    title: "Gelsemium Music Player";
    default-font-family: "League Mono";

    property <ScreenState> state: select;
    if state == ScreenState.select: PlaylistSelect{
        playlist_names: playlist_names;
        play_clicked(playlist_name) => {
            state = ScreenState.playing;
            play_playlist(playlist_name);
        };
        edit_clicked(playlist_name) => {
            state = ScreenState.editing;
            edit_playlist(playlist_name);
        }
    }
    if state == ScreenState.playing: PlayingMenu{
        playlist_queue: playlist_queue;
        user_queue: user_queue;
        currently_playing: currently_playing;
        library: library;
        skip => skip();
        pause => pause();
        library_elem_clicked(index) => library_elem_clicked(index);
        back_to_menu => {
            state = ScreenState.select;
            back_to_menu();
        }
    }
}


